version: "3.2"
services:
  app:
    build:
      context: .
      args:
        - REACT_APP_URL=http://localhost:3000
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
